#
#  Copyright 2015 VMware, Inc.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
---
- name: Prep wait
  wait_for: timeout=2

- name: install components CentOS
  yum: name={{ item }} state=present
  with_items:
   - xinetd
   - syslinux
   - tftp-server
   - httpd

- name: configure xinetd
  template: src=../templates/tftp dest=/etc/xinetd.d/tftp

- name: make tftp boot dir
  file: path={{ tftp_root }} state=directory mode=0777

- name: copy autodeploy zip
  copy: src="{{ autozip_src }}" dest="{{ tftp_root }}/deploy-tftpd.tbz2"

- name: unzip autodeploy zip
  command: chdir={{ tftp_root }} /bin/tar xvjf deploy-tftpd.tbz2
  
- name: create tramp file
  template: src=../templates/tramp dest="{{ tftp_root }}/tramp"

- name: rm autodeploy zip
  command: /bin/rm {{ tftp_root }}/deploy-tftpd.tbz2
  
- name: restart tftp service
  command: /sbin/service xinetd restart

- name: chkconfig tftp on
  command: /sbin/chkconfig xinetd on
