---
- name: allow all INPUT
  include: ubt_sec.yml

- name: install a known version of syslinux
  include: install_known_syslinux.yml

- name: install dhcp Centos
  include: ubt_dhcp.yml

- name: install tftp Centos
  include: ubt_tftp.yml
