---
- name: allow all INPUT
  command: /sbin/iptables -P INPUT ACCEPT

- name: flush iptables
  command: /sbin/iptables -F
  
- name: iptables conf centos
  template: src=../templates/iptables-config dest=/etc/sysconfig/iptables-config
  when: ansible_distribution == "CentOS" or ansible_distribution == "Red Hat Enterprise Linux" 

- name: save iptables
  command: /sbin/iptables-save
  notify: restart ufw
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: save iptables
  command: /sbin/iptables-save
  notify: restart iptables
  when: ansible_distribution == "CentOS" or ansible_distribution == "Red Hat Enterprise Linux"

- name: set selinux to permissive
  selinux: policy=targeted state=permissive
  when: ansible_distribution == "CentOS" or ansible_distribution == "Red Hat Enterprise Linux"
