---
- name: Prep for Installing Components
  wait_for: timeout=3

- name: install components CentOS
  yum: name={{ item }} state=present
  with_items:
   - xinetd
   - syslinux
   - tftp-server
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: install components Debian
  apt: name={{ item }} state=present
  with_items:
   - xinetd
   - tftpd
   - tftp
   - syslinux
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: configure xinetd
  template: src=../templates/tftp dest=/etc/xinetd.d/tftp
  notify: restart xinetd

- name: iptables-config
  template: src=../templates/iptables-config dest=/etc/sysconfig
  notify: restart iptables

- name: make tftp boot dir
  file: path={{ tftp_root }} state=directory

- name: file perms for tftproot
  file: path={{ tftp_root }} mode=0777

- name: copy autodeploy zip
  copy: src="{{ tftp_zip }}/deploy-tftpd.tbz2" dest=/tftpboot/deploy-tftpd.tbz2

- name: unzip autodeploy zip
  command: chdir={{ tftp_root }} /bin/tar xvjf deploy-tftpd.tbz2

- name: rm autodeploy zip
  command: chdir={{ tftp_root }} /bin/rm {{ tftp_root }}/deploy-tftpd.tbz2
