---
- name: install components ubuntu
  apt: name={{ item }} state=present
  with_items:
   - isc-dhcp-server

- name: configure isc-dhcp-server
  template: src=../templates/dhcpd.conf dest=/etc/dhcp/dhcpd.conf

- name: restart isc-dhcp-server service
  command: /usr/sbin/service isc-dhcp-server restart
